### PR TITLE
Bug/injector strictdi

### PR DESCRIPTION
**Pull request by herzinger**
Fix the angular error: 
```
[$injector:strictdi] $pgCheckout is not using explicit annotation and cannot be invoked in strict mode
```

Also, please, remember to publish the updates to npm as well. The current version is different from this repository.

### CODE REVIEW

**Comment by derekstavis** [comment]
Hi @herzinger, thanks for your pull request! :+1: 

I have noticed that you have reindented a big block of code in your PR. Although we like good indentation and we welcome it, we suggest that you send indentation fixes in a separate PR, for traceability reasons.

If you don't mind, please rebase your commits, keeping only the needed changes to fix the issue, and be welcome to send another PR with indentation fixes! :)

Thanks again for you contribution!!

**Comment by herzinger** [comment]
Sorry, my IDE is configured to automatically set indentation to 2 spaces. It should be okay now.
I can make a second PR with code organization if you'd like, but this one will fix the problem at hand.

**Comment by derekstavis** [comment]
Hey, thanks @herzinger, looks much better now :+1: 

cc\ @grvcoelho @felquis, could you guys take care of this and also give some tests?

**Comment by herzinger** [comment]
Please, give me a heads up when it's merged and published to NPM. I'm using it in production, so there should be no problems, but I would appreciate some testing, and I would prefere to use the package instead of my own copy of the file, as I'm doing right now.

**Comment by fesnt** [comment]
:+1:  I was having the unknown provider error, thanks a ton for this!

**Comment by herzinger** [comment]
@derekstavis The pull-request was merged, but it was never re-published to npm. The version there is still the same, and the bug is still there. You need to bump the version and publish it again for the change the apply.

**Pull request merged**
